server:
  port: 10224

spring:
  mvc:
    static-path-pattern=/static/**:
  mail:
    #邮件协议smtp
    host: smtp.163.com
    #发送者的邮件的用户名
    username: lwy2158223895@163.com
    #使用的编码
    default-encoding: utf-8
    #移动端客户授权码(在邮箱中设置)
    password: TSVSWNMMIHUDHUYY

